### ISSUE TITLE
Solve doesn't seem to support suc

### ISSUE THREAD

**Issue by mckeankylej** [oisdk/agda-ring-solver#11]
```agda
lemma : ∀ n → suc n ≡ suc n * 1
lemma n = solveOver (n ∷ []) Nat.ring
```
The code above fails with: 
```
/home/amckean/repos/thesis/proofs/Prelude/Nat.agda:123,11-38
n * 1 != n of type ℕ
when checking that the expression
Polynomial.Simple.Solver.Ops.correct {_} {_} Nat.ring {_}
(Polynomial.Expr.Expr._⊗_ {_}
 {AlmostCommutativeRing.Carrier {_} {_} Nat.ring} {1}
 (Polynomial.Expr.Expr.Κ {_}
  {AlmostCommutativeRing.Carrier {_} {_} Nat.ring} {1} (suc n))
 (Polynomial.Expr.Expr.Κ {_}
  {AlmostCommutativeRing.Carrier {_} {_} Nat.ring} {1} 1))
(Data.Vec.Base.Vec._∷_ {_} {_} {_} n
 (Data.Vec.Base.Vec.[] {_} {_}))
has type
(Nat.ring AlmostCommutativeRing.≈
 Polynomial.Simple.Solver.Ops.⟦ Nat.ring ⇓⟧
 (Polynomial.Expr.Expr.Κ (suc n))
 (n Data.Vec.Base.Vec.∷ Data.Vec.Base.Vec.[]))
_k_414
```
while the following type checks:
```agda
lemma : ∀ n → n ≡ n * 1
lemma n = solveOver (n ∷ []) Nat.ring
```
Is there a way to teach the solver about suc? All my proofs that include suc fail in a similar way.

**Comment by oisdk** [comment]
There is! It's a little ugly, though. You need to add a clause in the reflection code that catches `suc` and changes it to `1 +_`. This hack only works for Nat, but it *shouldn't* affect other types, so I think it's safe to do.

**Comment by oisdk** [comment]
Ok, I've added the ability to see `suc`. Turned out to be a one-liner!

**Comment by mckeankylej** [comment]
Wow thanks! On this topic it would be nice if the end user could introduce arbitrary preprocessing rules. So you could do the same thing that you did for nat but for any type.

**Comment by oisdk** [comment]
Yeah, unfortunately I haven't figured out a good way to do that. The solver itself can be accessed without reflection, of course, so you *could* write your own reflection logic that hooks up with the solver.
