### ISSUE TITLE
Does not type check with recent Agda.

### ISSUE THREAD

**Issue by kindaro** [oisdk/agda-ring-solver#14]
This project does not type check with the recent Agda, looks like Agda's internal types from `Agda.Builtin.Reflection` have been pulled out from under it.

This is the error:

```
/home/kindaro/code/agda/agda-ring-solver/src/Reflection/Helpers.agda:60,17-38
Relevance !=< Modality
when checking that the expression relevant has type Modality
```

This is the code:

```agda
infixr 5 _⋯⟅∷⟆_
_⋯⟅∷⟆_ : ℕ → List (Arg Term) → List (Arg Term)
zero  ⋯⟅∷⟆ xs = xs
suc i ⋯⟅∷⟆ xs = unknown ⟅∷⟆ i ⋯⟅∷⟆ xs
{-# INLINE _⋯⟅∷⟆_ #-}
```

I am trying to build the project with the latest Agda, built from source code today.

**Comment by kindaro** [comment]
Ah, I get it — this work has been merged as [`Tactic.RingSolver`](https://github.com/agda/agda-stdlib/blob/master/src/Tactic/RingSolver.agda). Maybe you can mark this repository as archived or something like that.

**Comment by oisdk** [comment]
You're right! I will
