### ISSUE TITLE
Issues regarding the compiler pragmas? (safe, without-K, etc.)

### ISSUE THREAD

**Issue by osense** [oisdk/agda-ring-solver#8]
Hi! First of all, thanks and congrats on completing what seems to be the most advanced solver for Agda, at least as far as reflection is involved (and probably in general).

I'm trying to use it and the code is failing to check, because it seems that a lot of modules in this project use various compiler options such as `--safe`, which only allow importing other modules that are also `safe`. Unfortunately, many modules in the Agda standard library are currently not `safe`, indeed [1] states that

> virtually any project relying on the standard library will not be successfully typechecked with the --`safe` option

When I try to type-check e.g. `Polynomial.Simple.Reflection`, indeed I get many errors regarding this:

```
/home/osense/dev/agda-libs/agda-ring-solver/src/Polynomial/Simple/Reflection.agda:5,1-23
Importing module Reflection not using the --safe flag from a module
which does.
when scope checking the declaration
  open import Reflection
/home/osense/dev/agda-libs/agda-ring-solver/src/Polynomial/Simple/Reflection.agda:5,1-23
Importing module Reflection not using the --without-K flag from a
module which does.
when scope checking the declaration
  open import Reflection
/home/osense/dev/agda-libs/agda-ring-solver/src/Polynomial/Simple/Reflection.agda:5,1-23
Importing module Reflection not using the --no-sized-types flag
from a module which does.
when scope checking the declaration
  open import Reflection
/home/osense/dev/agda-libs/agda-ring-solver/src/Polynomial/Simple/Reflection.agda:5,1-23
Importing module Reflection not using the --no-guardedness flag
from a module which does.
when scope checking the declaration
  open import Reflection
```

How do you manage to use the library in the current state? The above is using Agda `2.6.0` and version `0.17` of the standard library, but I have also tried the latest stdlib.

[1] https://agda.readthedocs.io/en/v2.5.4.1/language/safe-agda.html#standard-library

**Comment by oisdk** [comment]
Should work now!

**Comment by osense** [comment]
Thanks! Indeed it does :)
